import { Book } from '../types';

export const SEED_BOOKS: Book[] = [
  // Old Testament (1 - 39)
  { id: 1, book_order: 1, slug: 'genesis', testament: 'old', name_en: 'Genesis', name_am: 'ኦሪት ዘፍጥረት', name_he: 'בְּרֵאשִׁית', name_gr: 'Γένεσις', chapter_count: 50 },
  { id: 2, book_order: 2, slug: 'exodus', testament: 'old', name_en: 'Exodus', name_am: 'ኦሪት ዘጸአት', name_he: 'שְׁמוֹת', name_gr: 'Ἔξοδος', chapter_count: 40 },
  { id: 3, book_order: 3, slug: 'leviticus', testament: 'old', name_en: 'Leviticus', name_am: 'ኦሪት ዘሌዋውያን', name_he: 'וַיִּקְרָא', name_gr: 'Λευιτικόν', chapter_count: 27 },
  { id: 4, book_order: 4, slug: 'numbers', testament: 'old', name_en: 'Numbers', name_am: 'ኦሪት ዘኍልቍ', name_he: 'בְּמִדְבַּר', name_gr: 'Ἀριθμοί', chapter_count: 36 },
  { id: 5, book_order: 5, slug: 'deuteronomy', testament: 'old', name_en: 'Deuteronomy', name_am: 'ኦሪት ዘዳግም', name_he: 'דְּבָרִים', name_gr: 'Δευτερονόμιον', chapter_count: 34 },
  { id: 6, book_order: 6, slug: 'joshua', testament: 'old', name_en: 'Joshua', name_am: 'መጽሐፈ ኢያሱ', name_he: 'יְהוֹשֻׁעַ', name_gr: 'Ἰησοῦς', chapter_count: 24 },
  { id: 7, book_order: 7, slug: 'judges', testament: 'old', name_en: 'Judges', name_am: 'መጽሐፈ መሳፍንት', name_he: 'שֹׁפְטִים', name_gr: 'Κριταί', chapter_count: 21 },
  { id: 8, book_order: 8, slug: 'ruth', testament: 'old', name_en: 'Ruth', name_am: 'መጽሐፈ ሩት', name_he: 'רוּת', name_gr: 'Ῥούθ', chapter_count: 4 },
  { id: 9, book_order: 9, slug: '1-samuel', testament: 'old', name_en: '1 Samuel', name_am: 'መጽሐፈ ሳሙኤል ቀዳማዊ', name_he: 'שְׁמוּאֵל א׳', name_gr: 'Βασιλειῶν Αʹ', chapter_count: 31 },
  { id: 10, book_order: 10, slug: '2-samuel', testament: 'old', name_en: '2 Samuel', name_am: 'መጽሐፈ ሳሙኤል ካልእ', name_he: 'שְׁמוּאֵל ב׳', name_gr: 'Βασιλειῶν Βʹ', chapter_count: 24 },
  { id: 11, book_order: 11, slug: '1-kings', testament: 'old', name_en: '1 Kings', name_am: 'መጽሐፈ ነገሥት ቀዳማዊ', name_he: 'מְלָכִים א׳', name_gr: 'Βασιλειῶν Γʹ', chapter_count: 22 },
  { id: 12, book_order: 12, slug: '2-kings', testament: 'old', name_en: '2 Kings', name_am: 'መጽሐፈ ነገሥት ካልእ', name_he: 'מְלָכִים ב׳', name_gr: 'Βασιλειῶν Δʹ', chapter_count: 25 },
  { id: 13, book_order: 13, slug: '1-chronicles', testament: 'old', name_en: '1 Chronicles', name_am: 'መጽሐፈ ዜና መዋዕል ቀዳማዊ', name_he: 'דִּבְרֵי הַיָּמִים א׳', name_gr: 'Παραλειπομένων Αʹ', chapter_count: 29 },
  { id: 14, book_order: 14, slug: '2-chronicles', testament: 'old', name_en: '2 Chronicles', name_am: 'መጽሐፈ ዜና መዋዕል ካልእ', name_he: 'דִּבְרֵי הַיָּמִים ב׳', name_gr: 'Παραλειπομένων Βʹ', chapter_count: 36 },
  { id: 15, book_order: 15, slug: 'ezra', testament: 'old', name_en: 'Ezra', name_am: 'መጽሐፈ ዕዝራ', name_he: 'עֶזְרָא', name_gr: 'Ἔσδρας Βʹ', chapter_count: 10 },
  { id: 16, book_order: 16, slug: 'nehemiah', testament: 'old', name_en: 'Nehemiah', name_am: 'መጽሐፈ ነህምያ', name_he: 'נְחֶמְיָה', name_gr: 'Νεεμίας', chapter_count: 13 },
  { id: 17, book_order: 17, slug: 'esther', testament: 'old', name_en: 'Esther', name_am: 'መጽሐፈ አስቴር', name_he: 'אֶסְתֵּר', name_gr: 'Ἐσθήρ', chapter_count: 10 },
  { id: 18, book_order: 18, slug: 'job', testament: 'old', name_en: 'Job', name_am: 'መጽሐፈ ኢዮብ', name_he: 'אִיּוֹב', name_gr: 'Ἰώβ', chapter_count: 42 },
  { id: 19, book_order: 19, slug: 'psalms', testament: 'old', name_en: 'Psalms', name_am: 'መዝሙረ ዳዊት', name_he: 'תְּהִלִּים', name_gr: 'Ψαλμοί', chapter_count: 150 },
  { id: 20, book_order: 20, slug: 'proverbs', testament: 'old', name_en: 'Proverbs', name_am: 'መጽሐፈ ምሳሌ', name_he: 'מִשְׁלֵי', name_gr: 'Παροιμίαι', chapter_count: 31 },
  { id: 21, book_order: 21, slug: 'ecclesiastes', testament: 'old', name_en: 'Ecclesiastes', name_am: 'መጽሐፈ መክብብ', name_he: 'קֹהֶלֶת', name_gr: 'Ἐκκλησιαστής', chapter_count: 12 },
  { id: 22, book_order: 22, slug: 'song-of-solomon', testament: 'old', name_en: 'Song of Solomon', name_am: 'መኃልየ መኃልይ ዘሰሎሞን', name_he: 'שִׁיר הַשִּׁירִים', name_gr: 'ᾎσμα ᾈσμάτων', chapter_count: 8 },
  { id: 23, book_order: 23, slug: 'isaiah', testament: 'old', name_en: 'Isaiah', name_am: 'ትንቢተ ኢሳይያስ', name_he: 'יְשַׁעְיָהוּ', name_gr: 'Ἠσαΐας', chapter_count: 66 },
  { id: 24, book_order: 24, slug: 'jeremiah', testament: 'old', name_en: 'Jeremiah', name_am: 'ትንቢተ ኤርምያስ', name_he: 'יִרְמְיָהוּ', name_gr: 'Ἱερεμίας', chapter_count: 52 },
  { id: 25, book_order: 25, slug: 'lamentations', testament: 'old', name_en: 'Lamentations', name_am: 'ሰቆቃወ ኤርምያስ', name_he: 'אֵיכָה', name_gr: 'Θρῆνοι', chapter_count: 5 },
  { id: 26, book_order: 26, slug: 'ezekiel', testament: 'old', name_en: 'Ezekiel', name_am: 'ትንቢተ ሕዝቅኤል', name_he: 'יְחֶזְקֵאל', name_gr: 'Ἰεζεκιήλ', chapter_count: 48 },
  { id: 27, book_order: 27, slug: 'daniel', testament: 'old', name_en: 'Daniel', name_am: 'ትንቢተ ዳንኤል', name_he: 'דָּנִיֵּאל', name_gr: 'Δανιήλ', chapter_count: 12 },
  { id: 28, book_order: 28, slug: 'hosea', testament: 'old', name_en: 'Hosea', name_am: 'ትንቢተ ሆሴዕ', name_he: 'הוֹשֵׁעַ', name_gr: 'Ὡσηέ', chapter_count: 14 },
  { id: 29, book_order: 29, slug: 'joel', testament: 'old', name_en: 'Joel', name_am: 'ትንቢተ ኢዩኤል', name_he: 'יוֹאֵל', name_gr: 'Ἰωήλ', chapter_count: 3 },
  { id: 30, book_order: 30, slug: 'amos', testament: 'old', name_en: 'Amos', name_am: 'ትንቢተ አሞጽ', name_he: 'עָמוֹס', name_gr: 'Ἀμώς', chapter_count: 9 },
  { id: 31, book_order: 31, slug: 'obadiah', testament: 'old', name_en: 'Obadiah', name_am: 'ትንቢተ አብድዩ', name_he: 'עֹבַדְיָה', name_gr: 'Ὀβδιού', chapter_count: 1 },
  { id: 32, book_order: 32, slug: 'jonah', testament: 'old', name_en: 'Jonah', name_am: 'ትንቢተ ዮናስ', name_he: 'יוֹנָה', name_gr: 'Ἰωνᾶς', chapter_count: 4 },
  { id: 33, book_order: 33, slug: 'micah', testament: 'old', name_en: 'Micah', name_am: 'ትንቢተ ሚክያስ', name_he: 'מִיכָה', name_gr: 'Μιχαίας', chapter_count: 7 },
  { id: 34, book_order: 34, slug: 'nahum', testament: 'old', name_en: 'Nahum', name_am: 'ትንቢተ ናሆም', name_he: 'נַחוּם', name_gr: 'Ναούμ', chapter_count: 3 },
  { id: 35, book_order: 35, slug: 'habakkuk', testament: 'old', name_en: 'Habakkuk', name_am: 'ትንቢተ ዕንባቆም', name_he: 'חֲבַקּוּק', name_gr: 'Ἀμβακούμ', chapter_count: 3 },
  { id: 36, book_order: 36, slug: 'zephaniah', testament: 'old', name_en: 'Zephaniah', name_am: 'ትንቢተ ሶፎንያስ', name_he: 'צְפַנְיָה', name_gr: 'Σοφονίας', chapter_count: 3 },
  { id: 37, book_order: 37, slug: 'haggai', testament: 'old', name_en: 'Haggai', name_am: 'ትንቢተ ሐጌ', name_he: 'חַגַּי', name_gr: 'Ἁγγαῖος', chapter_count: 2 },
  { id: 38, book_order: 38, slug: 'zechariah', testament: 'old', name_en: 'Zechariah', name_am: 'ትንቢተ ዘካርያስ', name_he: 'זְכַרְיָה', name_gr: 'Ζαχαρίας', chapter_count: 14 },
  { id: 39, book_order: 39, slug: 'malachi', testament: 'old', name_en: 'Malachi', name_am: 'ትንቢተ ሚልክያስ', name_he: 'מַלְאָכִי', name_gr: 'Μαλαχίας', chapter_count: 4 },

  // New Testament (40 - 66)
  { id: 40, book_order: 40, slug: 'matthew', testament: 'new', name_en: 'Matthew', name_am: 'የማቴዎስ ወንጌል', name_he: null, name_gr: 'Κατὰ Μαθθαῖον', chapter_count: 28 },
  { id: 41, book_order: 41, slug: 'mark', testament: 'new', name_en: 'Mark', name_am: 'የማርቆስ ወንጌል', name_he: null, name_gr: 'Κατὰ Μᾶρκον', chapter_count: 16 },
  { id: 42, book_order: 42, slug: 'luke', testament: 'new', name_en: 'Luke', name_am: 'የሉቃስ ወንጌል', name_he: null, name_gr: 'Κατὰ Λουκᾶν', chapter_count: 24 },
  { id: 43, book_order: 43, slug: 'john', testament: 'new', name_en: 'John', name_am: 'የዮሐንስ ወንጌል', name_he: null, name_gr: 'Κατὰ Ἰωάννην', chapter_count: 21 },
  { id: 44, book_order: 44, slug: 'acts', testament: 'new', name_en: 'Acts', name_am: 'የሐዋርያት ሥራ', name_he: null, name_gr: 'Πράξεις τῶν Ἀποστόλων', chapter_count: 28 },
  { id: 45, book_order: 45, slug: 'romans', testament: 'new', name_en: 'Romans', name_am: 'ወደ ሮሜ ሰዎች', name_he: null, name_gr: 'Πρὸς Ῥωμαίους', chapter_count: 16 },
  { id: 46, book_order: 46, slug: '1-corinthians', testament: 'new', name_en: '1 Corinthians', name_am: '1ኛ ወደ ቆሮንቶስ ሰዎች', name_he: null, name_gr: 'Πρὸς Κορινθίους Αʹ', chapter_count: 16 },
  { id: 47, book_order: 47, slug: '2-corinthians', testament: 'new', name_en: '2 Corinthians', name_am: '2ኛ ወደ ቆሮንቶስ ሰዎች', name_he: null, name_gr: 'Πρὸς Κορινθίους Βʹ', chapter_count: 13 },
  { id: 48, book_order: 48, slug: 'galatians', testament: 'new', name_en: 'Galatians', name_am: 'ወደ ገላትያ ሰዎች', name_he: null, name_gr: 'Πρὸς Γαλάτας', chapter_count: 6 },
  { id: 49, book_order: 49, slug: 'ephesians', testament: 'new', name_en: 'Ephesians', name_am: 'ወደ ኤፌሶን ሰዎች', name_he: null, name_gr: 'Πρὸς Ἐφεσίους', chapter_count: 6 },
  { id: 50, book_order: 50, slug: 'philippians', testament: 'new', name_en: 'Philippians', name_am: 'ወደ ፊልጵስዩስ ሰዎች', name_he: null, name_gr: 'Πρὸς Φιλιππησίους', chapter_count: 4 },
  { id: 51, book_order: 51, slug: 'colossians', testament: 'new', name_en: 'Colossians', name_am: 'ወደ ቆላስይስ ሰዎች', name_he: null, name_gr: 'Πρὸς Κολοσσαεῖς', chapter_count: 4 },
  { id: 52, book_order: 52, slug: '1-thessalonians', testament: 'new', name_en: '1 Thessalonians', name_am: '1ኛ ወደ ተሰሎንቄ ሰዎች', name_he: null, name_gr: 'Πρὸς Θεσσαλονικεῖς Αʹ', chapter_count: 5 },
  { id: 53, book_order: 53, slug: '2-thessalonians', testament: 'new', name_en: '2 Thessalonians', name_am: '2ኛ ወደ ተሰሎንቄ ሰዎች', name_he: null, name_gr: 'Πρὸς Θεσσαλονικεῖς Βʹ', chapter_count: 3 },
  { id: 54, book_order: 54, slug: '1-timothy', testament: 'new', name_en: '1 Timothy', name_am: '1ኛ ወደ ጢሞቴዎስ', name_he: null, name_gr: 'Πρὸς Τιμόθεον Αʹ', chapter_count: 6 },
  { id: 55, book_order: 55, slug: '2-timothy', testament: 'new', name_en: '2 Timothy', name_am: '2ኛ ወደ ጢሞቴዎስ', name_he: null, name_gr: 'Πρὸς Τιμόθεον Βʹ', chapter_count: 4 },
  { id: 56, book_order: 56, slug: 'titus', testament: 'new', name_en: 'Titus', name_am: 'ወደ ቲቶ', name_he: null, name_gr: 'Πρὸς Τίτον', chapter_count: 3 },
  { id: 57, book_order: 57, slug: 'philemon', testament: 'new', name_en: 'Philemon', name_am: 'ወደ ፊልሞና', name_he: null, name_gr: 'Πρὸς Φιλήμονα', chapter_count: 1 },
  { id: 58, book_order: 58, slug: 'hebrews', testament: 'new', name_en: 'Hebrews', name_am: 'ወደ ዕብራውያን', name_he: null, name_gr: 'Πρὸς Ἑβραίους', chapter_count: 13 },
  { id: 59, book_order: 59, slug: 'james', testament: 'new', name_en: 'James', name_am: 'የያዕቆብ መልእክት', name_he: null, name_gr: 'Ἰακώβου', chapter_count: 5 },
  { id: 60, book_order: 60, slug: '1-peter', testament: 'new', name_en: '1 Peter', name_am: '1ኛ የጴጥሮስ መልእክት', name_he: null, name_gr: 'Πέτρου Αʹ', chapter_count: 5 },
  { id: 61, book_order: 61, slug: '2-peter', testament: 'new', name_en: '2 Peter', name_am: '2ኛ የጴጥሮስ መልእክት', name_he: null, name_gr: 'Πέτρου Βʹ', chapter_count: 3 },
  { id: 62, book_order: 62, slug: '1-john', testament: 'new', name_en: '1 John', name_am: '1ኛ የዮሐንስ መልእክት', name_he: null, name_gr: 'Ἰωάννου Αʹ', chapter_count: 5 },
  { id: 63, book_order: 63, slug: '2-john', testament: 'new', name_en: '2 John', name_am: '2ኛ የዮሐንስ መልእክት', name_he: null, name_gr: 'Ἰωάννου Βʹ', chapter_count: 1 },
  { id: 64, book_order: 64, slug: '3-john', testament: 'new', name_en: '3 John', name_am: '3ኛ የዮሐንስ መልእክት', name_he: null, name_gr: 'Ἰωάννου Γʹ', chapter_count: 1 },
  { id: 65, book_order: 65, slug: 'jude', testament: 'new', name_en: 'Jude', name_am: 'የይሁዳ መልእክት', name_he: null, name_gr: 'Ἰούδα', chapter_count: 1 },
  { id: 66, book_order: 66, slug: 'revelation', testament: 'new', name_en: 'Revelation', name_am: 'የዮሐንስ ራእይ', name_he: null, name_gr: 'Ἀποκάλυψις Ἰωάννου', chapter_count: 22 },
];
