export interface SeedVerseRecord {
  book_slug: string;
  chapter: number;
  verse_num: number;
  translation_code: string;
  text: string;
}

export const SEED_VERSES_RUTH: SeedVerseRecord[] = [
  // ==========================================
  // RUTH CHAPTER 1
  // ==========================================
  // English KJV
  { book_slug: 'ruth', chapter: 1, verse_num: 1, translation_code: 'eng-kjv', text: 'Now it came to pass in the days when the judges ruled, that there was a famine in the land. And a certain man of Bethlehemjudah went to sojourn in the country of Moab, he, and his wife, and his two sons.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 2, translation_code: 'eng-kjv', text: 'And the name of the man was Elimelech, and the name of his wife Naomi, and the name of his two sons Mahlon and Chilion, Ephrathites of Bethlehemjudah. And they came into the country of Moab, and continued there.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 3, translation_code: 'eng-kjv', text: 'And Elimelech Naomi\'s husband died; and she was left, and her two sons.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 4, translation_code: 'eng-kjv', text: 'And they took them wives of the women of Moab; the name of the one was Orpah, and the name of the other Ruth: and they dwelled there about ten years.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 5, translation_code: 'eng-kjv', text: 'And Mahlon and Chilion died also both of them; and the woman was left of her two sons and her husband.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 6, translation_code: 'eng-kjv', text: 'Then she arose with her daughters in law, that she might return from the country of Moab: for she had heard in the country of Moab how that the LORD had visited his people in giving them bread.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 7, translation_code: 'eng-kjv', text: 'Wherefore she went forth out of the place where she was, and her two daughters in law with her; and they went on the way to return unto the land of Judah.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 8, translation_code: 'eng-kjv', text: 'And Naomi said unto her two daughters in law, Go, return each to her mother\'s house: the LORD deal kindly with you, as ye have dealt with the dead, and with me.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 9, translation_code: 'eng-kjv', text: 'The LORD grant you that ye may find rest, each of you in the house of her husband. Then she kissed them; and they lifted up their voice, and wept.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 10, translation_code: 'eng-kjv', text: 'And they said unto her, Surely we will return with thee unto thy people.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 11, translation_code: 'eng-kjv', text: 'And Naomi said, Turn again, my daughters: why will ye go with me? are there yet any more sons in my womb, that they may be your husbands?' },
  { book_slug: 'ruth', chapter: 1, verse_num: 12, translation_code: 'eng-kjv', text: 'Turn again, my daughters, go your way; for I am too old to have an husband. If I should say, I have hope, if I should have an husband also to night, and should also bear sons;' },
  { book_slug: 'ruth', chapter: 1, verse_num: 13, translation_code: 'eng-kjv', text: 'Would ye tarry for them till they were grown? would ye stay for them from having husbands? nay, my daughters; for it grieveth me much for your sakes that the hand of the LORD is gone out against me.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 14, translation_code: 'eng-kjv', text: 'And they lifted up their voice, and wept again: and Orpah kissed her mother in law; but Ruth clave unto her.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 15, translation_code: 'eng-kjv', text: 'And she said, Behold, thy sister in law is gone back unto her people, and unto her gods: return thou after thy sister in law.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 16, translation_code: 'eng-kjv', text: 'And Ruth said, Intreat me not to leave thee, or to return from following after thee: for whither thou goest, I will go; and where thou lodgest, I will lodge: thy people shall be my people, and thy God my God:' },
  { book_slug: 'ruth', chapter: 1, verse_num: 17, translation_code: 'eng-kjv', text: 'Where thou diest, will I die, and there will I be buried: the LORD do so to me, and more also, if ought but death part thee and me.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 18, translation_code: 'eng-kjv', text: 'When she saw that she was stedfastly minded to go with her, then she left speaking unto her.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 19, translation_code: 'eng-kjv', text: 'So they two went until they came to Bethlehem. And it came to pass, when they were come to Bethlehem, that all the city was moved about them, and they said, Is this Naomi?' },
  { book_slug: 'ruth', chapter: 1, verse_num: 20, translation_code: 'eng-kjv', text: 'And she said unto them, Call me not Naomi, call me Mara: for the Almighty hath dealt very bitterly with me.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 21, translation_code: 'eng-kjv', text: 'I went out full, and the LORD hath brought me home again empty: why then call ye me Naomi, seeing the LORD hath testified against me, and the Almighty hath afflicted me?' },
  { book_slug: 'ruth', chapter: 1, verse_num: 22, translation_code: 'eng-kjv', text: 'So Naomi returned, and Ruth the Moabitess, her daughter in law, with her, which returned out of the country of Moab: and they came to Bethlehem in the beginning of barley harvest.' },

  // Amharic 1875 Abu Rumi
  { book_slug: 'ruth', chapter: 1, verse_num: 1, translation_code: 'am-1875', text: 'መሳፍንት በሚፈርዱበት ዘመን በምድሪቱ ራብ ሆነ፤ ከይሁዳ ቤተ ልሔምም አንድ ሰው ከሚስቱና ከሁለት ልጆቹ ጋር በሞዓብ ምድር ሊቀመጥ ሄደ።' },
  { book_slug: 'ruth', chapter: 1, verse_num: 2, translation_code: 'am-1875', text: 'የሰውየውም ስም አቤሜሌክ፥ የሚስቱም ስም ኑኃሚን፥ የሁለቱ ልጆቹም ስም መሐሎንና ኬሌዎን ነበረ፤ የይሁዳ ቤተ ልሔም ኤፍራታውያን ነበሩ። ወደ ሞዓብም ምድር መጥተው በዚያ ተቀመጡ።' },
  { book_slug: 'ruth', chapter: 1, verse_num: 3, translation_code: 'am-1875', text: 'የኑኃሚንም ባል አቤሜሌክ ሞተ፤ እርስዋና ሁለቱ ልጆችዋ ቀሩ።' },
  { book_slug: 'ruth', chapter: 1, verse_num: 4, translation_code: 'am-1875', text: 'እነርሱም ከሞዓባውያን ሴቶች ሚስቶችን አገቡ፤ የአንዲቱ ስም ዖርፋ፥ የሁለተኛይቱም ስም ሩት ነበረ፤ በዚያም አሥር ዓመት ያህል ተቀመጡ።' },
  { book_slug: 'ruth', chapter: 1, verse_num: 5, translation_code: 'am-1875', text: 'መሐሎንና ኬሌዎንም ሁለቱ ሞቱ፤ ሴቲቱም ከሁለቱ ልጆችዋና ከባልዋ ተለይታ ብቻዋን ቀረች።' },
  { book_slug: 'ruth', chapter: 1, verse_num: 6, translation_code: 'am-1875', text: 'እግዚአብሔርም ለሕዝቡ እንጀራ እንደ ሰጣቸው በሞዓብ ምድር ስለ ሰማች፥ ከምራቶችዋ ጋር ከሞዓብ ምድር ልትመለስ ተነሣች።' },
  { book_slug: 'ruth', chapter: 1, verse_num: 7, translation_code: 'am-1875', text: 'ከነበረችበትም ስፍራ ሁለቱም ምራቶችዋ ከእርስዋ ጋር ወጡ፥ ወደ ይሁዳም ምድር ለመመለስ በመንገድ ሄዱ።' },
  { book_slug: 'ruth', chapter: 1, verse_num: 8, translation_code: 'am-1875', text: 'ኑኃሚንም ሁለቱን ምራቶችዋን፦ ሒዱ፥ እያንዳንዳችሁ ወደ እናታችሁ ቤት ተመለሱ፤ በሞቱትም በእኔም እንዳደረጋችሁ፥ እግዚአብሔር ቸርነትን ያድርግላችሁ።' },
  { book_slug: 'ruth', chapter: 1, verse_num: 9, translation_code: 'am-1875', text: 'እግዚአብሔርም በእያንዳንዳችሁ ባል ቤት ዕረፍትን ይስጣችሁ አለቻቸው። ሳመቻቸውም፥ ድምፃቸውንም አንሥተው አለቀሱ።' },
  { book_slug: 'ruth', chapter: 1, verse_num: 10, translation_code: 'am-1875', text: 'እነርሱም፦ ከአንቺ ጋር ወደ ሕዝብሽ እንመለሳለን አሉአት።' },
  { book_slug: 'ruth', chapter: 1, verse_num: 11, translation_code: 'am-1875', text: 'ኑኃሚንም አለች፦ ልጆቼ ሆይ፥ ተመለሱ፤ ለምንስ ከእኔ ጋር ትሄዳላችሁ? ባሎች የሚሆኑአችሁ ልጆች ገና በማኅፀኔ አሉኝን?' },
  { book_slug: 'ruth', chapter: 1, verse_num: 12, translation_code: 'am-1875', text: 'ልጆቼ ሆይ፥ ተመለሱ፥ ሒዱ፤ እኔ ለባል መሆን አርጅቻለሁና። ተስፋ አለኝ ብል፥ በዚህችም ሌሊት ለባል ብሆን፥ ደግሞም ወንዶች ልጆችን ብወልድ፥' },
  { book_slug: 'ruth', chapter: 1, verse_num: 13, translation_code: 'am-1875', text: 'እነርሱ እስኪያድጉ ድረስ ትጠብቃላችሁን? ባል ከማግባትስ ተከልክላችሁ ትቀመጣላችሁን? ልጆቼ ሆይ፥ አይሆንም፤ የእግዚአብሔር እጅ በእኔ ላይ ወጥታለችና ከእናንተ ይልቅ ስለ እናንተ እጅግ መሮኛል።' },
  { book_slug: 'ruth', chapter: 1, verse_num: 14, translation_code: 'am-1875', text: 'ድምፃቸውንም አንሥተው ደግመው አለቀሱ፤ ዖርፋም አማትዋን ሳመቻት፥ ሩት ግን ተጣበቀቻት።' },
  { book_slug: 'ruth', chapter: 1, verse_num: 15, translation_code: 'am-1875', text: 'እርስዋም፦ እነሆ፥ ባልንጀራሽ ወደ ሕዝብዋና ወደ አማልክትዋ ተመልሳለች፤ አንቺም ደግሞ ከባልንጀራሽ በኋላ ተመለሺ አለቻት።' },
  { book_slug: 'ruth', chapter: 1, verse_num: 16, translation_code: 'am-1875', text: 'ሩትም አለች፦ ወደምትሄጂበት እሄዳለሁና፥ በምታድሪበትም አድራለሁና፥ ከአንቺ ዘንድ እንድመለስ አታስቸግሪኝ፤ ሕዝብሽ ሕዝቤ፥ አምላክሽም አምላኬ ይሆናል።' },
  { book_slug: 'ruth', chapter: 1, verse_num: 17, translation_code: 'am-1875', text: 'በምትሞቺበት ስፍራ እሞታለሁ፥ በዚያም እቀበራለሁ፤ ከሞት በቀር ከአንቺ ቢለየኝ፥ እግዚአብሔር ይህን ያድርግብኝ፥ ይህም ይጨምርብኝ።' },
  { book_slug: 'ruth', chapter: 1, verse_num: 18, translation_code: 'am-1875', text: 'ከእርስዋ ጋር ለመሄድ እንደ ቈረጠች ባየች ጊዜ፥ ከእርስዋ ጋር መነጋገርን ተወች።' },
  { book_slug: 'ruth', chapter: 1, verse_num: 19, translation_code: 'am-1875', text: 'ሁለቱም ወደ ቤተ ልሔም እስኪደርሱ ድረስ ሄዱ። ወደ ቤተ ልሔምም በደረሱ ጊዜ ከተማይቱ ሁሉ ስለ እነርሱ ተናወጠች፥ ሴቶቹም፦ ይህች ኑኃሚን ናትን? አሉ።' },
  { book_slug: 'ruth', chapter: 1, verse_num: 20, translation_code: 'am-1875', text: 'እርስዋም፦ ሁሉን የሚችል አምላክ እጅግ አስመርሮኛልና ማራ በሉኝ እንጂ ኑኃሚን አትበሉኝ፤' },
  { book_slug: 'ruth', chapter: 1, verse_num: 21, translation_code: 'am-1875', text: 'እኔ ሙሉ ሆኜ ወጥቼ ነበር፥ እግዚአብሔርም ባዶዬን መለሰኝ፤ እግዚአብሔር አዋርዶኝ፥ ሁሉንም የሚችል አምላክ አስጨንቆኝ ሳለ፥ ለምን ኑኃሚን ብላችሁ ትጠሩኛላችሁ? አለች።' },
  { book_slug: 'ruth', chapter: 1, verse_num: 22, translation_code: 'am-1875', text: 'እንዲሁም ኑኃሚን ከሞዓብ ምድር የተመለሰችውን ምራቷን ሞዓባዊቱን ሩትን ይዛ ተመለሰች፤ እነርሱም የገብስ መከር በሚጀመርበት ጊዜ ወደ ቤተ ልሔም ደረሱ።' },

  // Hebrew Masoretic Text (WLC)
  { book_slug: 'ruth', chapter: 1, verse_num: 1, translation_code: 'heb-wlc', text: 'וַיְהִ֗י בִּימֵי֙ שְׁפֹ֣ט הַשֹּׁפְטִ֔ים וַיְהִ֥י רָעָ֖ב בָּאָ֑רֶץ וַיֵּ֨לֶךְ אִ֜ישׁ מִבֵּ֥ית לֶ֙חֶם֙ יְהוּדָ֔ה לָגּוּר֙ בִּשְׂדֵ֣י מוֹאָ֔ב ה֥וּא וְאִשְׁתּ֖וֹ וּשְׁנֵ֥י בָנָֽיו׃' },
  { book_slug: 'ruth', chapter: 1, verse_num: 2, translation_code: 'heb-wlc', text: 'וְשֵׁ֣ם הָאִ֣ישׁ אֱֽלִימֶ֡לֶךְ וְשֵׁם֩ אִשְׁתּ֨וֹ נָעֳמִ֜י וְשֵׁ֥ם שְׁנֵֽי־בָנָ֣יו ׀ מַחְל֤וֹן וְכִלְיוֹן֙ אֶפְרָתִ֔ים מִבֵּ֥ית לֶ֖חֶם יְהוּדָ֑ה וַיָּבֹ֥אוּ שְׂדֵי־מוֹאָ֖ב וַיִּֽהְיוּ־שָֽׁם׃' },
  { book_slug: 'ruth', chapter: 1, verse_num: 3, translation_code: 'heb-wlc', text: 'וַיָּ֥מָת אֱלִימֶ֖לֶךְ אִ֣ישׁ נָעֳמִ֑י וַתִּשָּׁאֵ֥ר הִ֖יא וּשְׁנֵ֥י בָנֶֽיהָ׃' },
  { book_slug: 'ruth', chapter: 1, verse_num: 4, translation_code: 'heb-wlc', text: 'וַיִּשְׂא֣וּ לָהֶ֗ם נָשִׁים֙ מֹֽאֲבִיּ֔וֹת שֵׁ֤ם הָאַחַת֙ עָרְפָּ֔ה וְשֵׁ֥ם הַשֵּׁנִ֖ית ר֑וּת וַיֵּ֥שְׁבוּ שָׁ֖ם כְּעֶ֥שֶׂר שָׁנִֽים׃' },
  { book_slug: 'ruth', chapter: 1, verse_num: 5, translation_code: 'heb-wlc', text: 'וַיָּמ֥וּתוּ גַם־שְׁנֵיהֶ֖ם מַחְל֣וֹן וְכִלְי֑וֹן וַתִּשָּׁאֵר֙ הָֽאִשָּׁ֔ה מִשְּׁנֵ֥י יְלָדֶ֖יהָ וּמֵאִישָֽׁהּ׃' },
  { book_slug: 'ruth', chapter: 1, verse_num: 6, translation_code: 'heb-wlc', text: 'וַתָּ֤קָם הִיא֙ וְכַלֹּתֶ֔יהָ וַתָּ֖שָׁב מִשְּׂדֵ֣י מוֹאָ֑ב כִּ֤י שָֽׁמְעָה֙ בִּשְׂדֵ֣ה מוֹאָ֔ב כִּֽי־פָקַ֤ד יְהוָה֙ אֶת־עַמּ֔וֹ לָתֵ֥ת לָהֶ֖ם לָֽחֶם׃' },
  { book_slug: 'ruth', chapter: 1, verse_num: 7, translation_code: 'heb-wlc', text: 'וַתֵּצֵ֗א מִן־הַמָּקוֹם֙ אֲשֶׁ֣ר הָיְתָה־שָּׁ֔מָּה וּשְׁתֵּ֥י כַלּוֹתֶ֖יהָ עִמָּ֑הּ וַתֵּלַ֣כְנָה בַדֶּ֔רֶךְ לָשׁ֖וּב אֶל־אֶ֥רֶץ יְהוּדָֽה׃' },
  { book_slug: 'ruth', chapter: 1, verse_num: 8, translation_code: 'heb-wlc', text: 'וַתֹּ֤אמֶר נָעֳמִי֙ לִשְׁתֵּ֣י כַלֹּתֶ֔יהָ לֵ֣כְנָה שֹּׁ֔בְנָה אִשָּׁ֖ה לְבֵ֣ית אִמָּ֑הּ יַעֲשֶׂ֤ה יְהוָה֙ עִמָּכֶ֣ם חֶ֔סֶד כַּאֲשֶׁ֧ר עֲשִׂיתֶ֛ם עִם־הַמֵּתִ֖ים וְעִמָּדִֽי׃' },
  { book_slug: 'ruth', chapter: 1, verse_num: 9, translation_code: 'heb-wlc', text: 'יִתֵּ֤ן יְהוָה֙ לָכֶ֔ם וּמְצֶ֣אןָ מְנוּחָ֔ה אִשָּׁ֖ה בֵּ֣ית אִישָׁ֑הּ וַתִּשַּׁ֣ק לָהֶ֔ן וַתִּשֶּׂ֥אנָה קוֹלָ֖ן וַתִּבְכֶּֽינָה׃' },
  { book_slug: 'ruth', chapter: 1, verse_num: 10, translation_code: 'heb-wlc', text: 'וַתֹּאמַ֖רְנָה־לָּ֑הּ כִּי־אִתָּ֥ךְ נָשׁ֖וּב לְעַמֵּֽךְ׃' },
  { book_slug: 'ruth', chapter: 1, verse_num: 11, translation_code: 'heb-wlc', text: 'וַתֹּ֤אמֶר נָעֳמִי֙ שֹׁ֣בְנָה בְנֹתַ֔י לָ֥מָּה תֵלַ֖כְנָה עִמָּ֑דִי הַֽעֽוֹד־לִ֤י בָנִים֙ בְּֽמֵעַ֔י וְהָי֥וּ לָכֶ֖ם לַאֲנָשִֽׁים׃' },
  { book_slug: 'ruth', chapter: 1, verse_num: 12, translation_code: 'heb-wlc', text: 'שֹׁ֤בְנָה בְנֹתַי֙ לֵ֔כְןָ כִּ֥י זָקַ֖נְתִּי מִהְי֣וֹת לְאִ֑ישׁ כִּ֤י אָמַ֙רְתִּי֙ יֶשׁ־לִ֣י תִקְוָ֔ה גַּ֣ם הָיִ֤יתִי הַלַּ֙יְלָה֙ לְאִ֔ישׁ וְגַ֖ם יָלַ֥דְתִּי בָנִֽים׃' },
  { book_slug: 'ruth', chapter: 1, verse_num: 13, translation_code: 'heb-wlc', text: 'הֲלָהֵ֣ן ׀ תְּשַׂבֵּ֗רְנָה עַ֚ד אֲשֶׁ֣ר יִגְדָּ֔לוּ הֲלָהֵן֙ תֵּעָגֵ֔נָה לְבִלְתִּ֖י הֱי֣וֹת לְאִ֑ישׁ אַ֣ל בְּנֹתַ֗י כִּֽי־מַר־לִ֤י מְאֹד֙ מִכֶּ֔ם כִּֽי־יָצְאָ֥ה בִ֖י יַד־יְהוָֽה׃' },
  { book_slug: 'ruth', chapter: 1, verse_num: 14, translation_code: 'heb-wlc', text: 'וַתִּשֶּׂ֣אנָה קוֹלָ֔ן וַתִּבְכֶּ֖ינָה ע֑וֹד וַתִּשַּׁ֤ק עָרְפָּה֙ לַחֲמוֹתָ֔הּ וְר֖וּת דָּ֥בְקָה בָּֽהּ׃' },
  { book_slug: 'ruth', chapter: 1, verse_num: 15, translation_code: 'heb-wlc', text: 'וַתֹּ֗אמֶר הִנֵּה֙ שָׁ֣בָה יְבִמְתֵּ֔ךְ אֶל־עַמָּ֖הּ וְאֶל־אֱלֹהֶ֑יהָ שׁ֖וּבִי אַחֲרֵ֥י יְבִמְתֵּֽךְ׃' },
  { book_slug: 'ruth', chapter: 1, verse_num: 16, translation_code: 'heb-wlc', text: 'וַתֹּ֤אמֶר רוּת֙ אַל־תִּפְגְּעִי־בִ֔י לְעָזְבֵ֖ךְ לָשׁ֣וּב מֵאַחֲרָ֑יִךְ כִּ֠י אֶל־אֲשֶׁ֨ר תֵּלְכִ֜י אֵלֵ֗ךְ וּבַאֲשֶׁ֤ר תָּלִ֙ינִי֙ אָלִ֔ין עַמֵּ֣ךְ עַמִּ֔י וֵאלֹהַ֖יִךְ אֱלֹהָֽי׃' },
  { book_slug: 'ruth', chapter: 1, verse_num: 17, translation_code: 'heb-wlc', text: 'בַּאֲשֶׁ֤ר תָּמ֙וּתִי֙ אָמ֔וּת וְשָׁ֖ם אֶקָּבֵ֑ר כֹּה֩ יַעֲשֶׂ֨ה יְהוָ֥ה לִי֙ וְכֹ֣ה יוֹסִ֔יף כִּ֣י הַמָּ֔וֶת יַפְרִ֖יד בֵּינִ֥י וּבֵינֵֽךְ׃' },
  { book_slug: 'ruth', chapter: 1, verse_num: 18, translation_code: 'heb-wlc', text: 'וַתֵּ֕רֶא כִּֽי־מִתְאַמֶּ֥צֶת הִ֖יא לָלֶ֣כֶת אִתָּ֑הּ וַתֶּחְדַּ֖ל לְדַבֵּ֥ר אֵלֶֽיהָ׃' },
  { book_slug: 'ruth', chapter: 1, verse_num: 19, translation_code: 'heb-wlc', text: 'וַתֵּלַ֣כְנָה שְׁתֵּיהֶ֔ם עַד־בּוֹאָ֖נָה בֵּ֣ית לָ֑חֶם וַיְהִ֗י כְּבוֹאָ֙נָה֙ בֵּ֣ית לֶ֔חֶם וַתֵּהֹ֤ם כָּל־הָעִיר֙ עֲלֵיהֶ֔ן וַתֹּאמַ֖רְנָה הֲזֹ֥את נָעֳמִֽי׃' },
  { book_slug: 'ruth', chapter: 1, verse_num: 20, translation_code: 'heb-wlc', text: 'וַתֹּ֣אמֶר אֲלֵיהֶ֔ן אַל־תִּקְרֶ֥אנָה לִ֖י נָעֳמִ֑י קְרֶ֤אןָ לִי֙ מָרָ֔א כִּי־הֵמַ֥ר שַׁדַּ֛י לִ֖י מְאֹֽד׃' },
  { book_slug: 'ruth', chapter: 1, verse_num: 21, translation_code: 'heb-wlc', text: 'אֲנִי֙ מְלֵאָ֣ה הָלַ֔כְתִּי וְרֵיקָ֖ם הֱשִׁיבַ֣נִי יְהוָ֑ה לָ֣מָּה תִקְרֶ֤אנָה לִי֙ נָעֳמִ֔י וַֽיהוָה֙ עָ֣נָה בִ֔י וְשַׁדַּ֖י הֵ֥רַֽע לִֽי׃' },
  { book_slug: 'ruth', chapter: 1, verse_num: 22, translation_code: 'heb-wlc', text: 'וַתָּ֣שָׁב נָעֳמִ֗י וְר֨וּת הַמּוֹאֲבִיָּ֤ה כַלָּתָהּ֙ עִמָּ֔הּ הַשָּׁ֖בָה מִשְּׂדֵ֣י מוֹאָ֑ב וְהֵ֗מָּה בָּ֚אוּ בֵּ֣ית לֶ֔חֶם בִּתְחִלַּ֖ת קְצִ֥יר שְׂעֹרִֽים׃' },

  // Greek (Septuagint LXX)
  { book_slug: 'ruth', chapter: 1, verse_num: 1, translation_code: 'grc-sblgnt', text: 'Καὶ ἐγένετο ἐν τῷ κρίνειν τοὺς κριτὰς καὶ ἐγένετο λιμὸς ἐν τῇ γῇ· καὶ ἐπορεύθη ἀνὴρ ἀπὸ Βηθλεεμ τῆς Ιουδα τοῦ παροικῆσαι ἐν ἀγρῷ Μωαβ, αὐτὸς καὶ ἡ γυνὴ αὐτοῦ καὶ οἱ υἱοὶ αὐτοῦ.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 2, translation_code: 'grc-sblgnt', text: 'Καὶ ὄνομα τῷ ἀνδρὶ Αβιμελεχ καὶ ὄνομα τῇ γυναικὶ αὐτοῦ Νωεμιν καὶ ὄνομα τοῖς δυσὶν υἱοῖς αὐτοῦ Μααλων καὶ Χελαιων, Εφραθαῖοι ἐκ Βηθλεεμ τῆς Ιουδα· καὶ ἦλθον εἰς ἀγρὸν Μωαβ καὶ ἦσαν ἐκεῖ.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 3, translation_code: 'grc-sblgnt', text: 'Καὶ ἀπέθανεν Αβιμελεχ ὁ ἀνὴρ τῆς Νωεμιν, καὶ κατελείφθη αὐτὴ καὶ οἱ δύο υἱοὶ αὐτῆς.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 4, translation_code: 'grc-sblgnt', text: 'Καὶ ἐλάβοσαν ἑαυτοῖς γυναῖκας Μωαβίτιδας, ὄνομα τῇ μιᾷ Ορφα καὶ ὄνομα τῇ δευτέρᾳ Ρουθ· καὶ κατῴκησαν ἐκεῖ ὡς δέκα ἔτη.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 5, translation_code: 'grc-sblgnt', text: 'Καὶ ἀπέθανον ἀμφότεροι, Μααλων καὶ Χελαιων, καὶ κατελείφθη ἡ γυνὴ ἀπὸ τῶν δύο υἱῶν αὐτῆς καὶ ἀπὸ τοῦ ἀνδρὸς αὐτῆς.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 6, translation_code: 'grc-sblgnt', text: 'Καὶ ἀνέστη αὐτὴ καὶ αἱ νύμφαι αὐτῆς καὶ ἀπέστρεψαν ἐξ ἀγροῦ Μωαβ, ὅτι ἤκουσεν ἐν ἀγρῷ Μωαβ ὅτι ἐπέσκεπται Κύριος τὸν λαὸν αὐτοῦ δοῦναι αὐτοῖς ἄρτους.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 7, translation_code: 'grc-sblgnt', text: 'Καὶ ἐξῆλθεν ἐκ τοῦ τόπου οὗ ἦν ἐκεῖ, καὶ αἱ δύο νύμφαι αὐτῆς μετʼ αὐτῆς· καὶ ἐπορεύοντο ἐν τῇ ὁδῷ τοῦ ἐπιστρέψαι εἰς τὴν γῆν Ιουδα.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 8, translation_code: 'grc-sblgnt', text: 'Καὶ εἶπεν Νωεμιν ταῖς νύμφαις αὐτῆς Πορεύεσθε δὴ ἀποστράφητε ἑκάστη εἰς οἶκον μητρὸς αὐτῆς· ποιήσαι Κύριος μεθʼ ὑμῶν ἔλεος, καθὼς ἐποιήσατε μετὰ τῶν τεθνηκότων καὶ μετʼ ἐμοῦ·' },
  { book_slug: 'ruth', chapter: 1, verse_num: 9, translation_code: 'grc-sblgnt', text: 'δῴη Κύριος ὑμῖν καὶ εὕροιτε ἀνάπαυσιν ἑκάστη ἐν οἴκῳ ἀνδρὸς αὐτῆς. καὶ κατεφίλησεν αὐτάς· καὶ ἐπῆραν τὴν φωνὴν αὐτῶν καὶ ἔκλαυσαν' },
  { book_slug: 'ruth', chapter: 1, verse_num: 10, translation_code: 'grc-sblgnt', text: 'καὶ εἶπαν αὐτῇ Μετὰ σοῦ ἐπιστρέφομεν εἰς τὸν λαόν σου.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 11, translation_code: 'grc-sblgnt', text: 'Καὶ εἶπεν Νωεμιν Ἐπιστράφητε δή, θυγατέρες μου· ἱνατί πορεύεσθε μετʼ ἐμοῦ; μὴ ἔτι μοι υἱοὶ ἐν τῇ κοιλίᾳ μου καὶ ἔσονται ὑμῖν εἰς ἄνδρας;' },
  { book_slug: 'ruth', chapter: 1, verse_num: 12, translation_code: 'grc-sblgnt', text: 'ἐπιστράφητε δή, θυγατέρες μου, διότι γεγήρακα τοῦ μὴ εἶναι ἀνδρί· ὅτι εἶπα ὅτι ἔστιν μοι ὑπόστασις τοῦ γενηθῆναί με ἀνδρὶ καὶ τέξομαι υἱούς,' },
  { book_slug: 'ruth', chapter: 1, verse_num: 13, translation_code: 'grc-sblgnt', text: 'μὴ αὐτοὺς προσδέξεσθε ἕως οὗ ἁδρυνθῶσιν; ἢ αὐτοῖς κατασχεθήσεσθε τοῦ μὴ γενέσθαι ἀνδρί; μὴ δή, θυγατέρες μου, ὅτι ἐπικράνθη μοι ὑπὲρ ὑμᾶς, ὅτι ἐξῆλθεν ἐν ἐμοὶ χεὶρ Κυρίου.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 14, translation_code: 'grc-sblgnt', text: 'Καὶ ἐπῆραν τὴν φωνὴν αὐτῶν καὶ ἔκλαυσαν ἔτι. καὶ κατεφίλησεν Ορφα τὴν πενθερὰν αὐτῆς, Ρουθ δὲ ἠκολούθησεν αὐτῇ.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 15, translation_code: 'grc-sblgnt', text: 'Καὶ εἶπεν Νωεμιν πρὸς Ρουθ Ἰδοὺ ἀνέστρεψεν ἡ σύννυμφός σου πρὸς λαὸν αὐτῆς καὶ πρὸς τοὺς θεοὺς αὐτῆς· ἐπίστρεψον δὴ καὶ σὺ ὀπίσω τῆς συννύμφου σου.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 16, translation_code: 'grc-sblgnt', text: 'Εἶπεν δὲ Ρουθ Μὴ ἀπαντήσαι ἐμοὶ τοῦ καταλιπεῖν σε ἢ ἀποστρέψαι ὄπισθέν σου· ὅτι σὺ ὅπου ἐὰν πορευθῇς, πορεύσομαι, καὶ οὗ ἐὰν αὐλισθῇς, αὐλισθήσομαι· ὁ λαός σου λαός μου, καὶ ὁ θεός σου θεός μου·' },
  { book_slug: 'ruth', chapter: 1, verse_num: 17, translation_code: 'grc-sblgnt', text: 'καὶ οὗ ἐὰν ἀποθάνῃς, ἀποθανοῦμαι κἀκεῖ ταφήσομαι· τάδε ποιήσαι μοι Κύριος καὶ τάδε προσθείη, ὅτι θάνατος διαστελεῖ ἀνὰ μέσον ἐμοῦ καὶ σοῦ.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 18, translation_code: 'grc-sblgnt', text: 'Ἰδοῦσα δὲ Νωεμιν ὅτι κραταιοῦται αὐτὴ τοῦ πορεύεσθαι μετʼ αὐτῆς, ἐκόπασεν τοῦ λαλῆσαι πρὸς αὐτὴν ἔτι.' },
  { book_slug: 'ruth', chapter: 1, verse_num: 19, translation_code: 'grc-sblgnt', text: 'Ἐπορεύθησαν δὲ ἀμφότεραι ἕως τοῦ παραγενέσθαι αὐτὰς εἰς Βηθλεεμ. καὶ ἤχησεν πᾶσα ἡ πόλις ἐπʼ αὐταῖς, καὶ εἶπον Αὕτη ἐστὶν Νωεμιν;' },
  { book_slug: 'ruth', chapter: 1, verse_num: 20, translation_code: 'grc-sblgnt', text: 'Καὶ εἶπεν πρὸς αὐτάς Μὴ δή καλεῖτέ με Νωεμιν, καλέσατέ με Πικράν, ὅτι ἐπικράνθη ἐν ἐμοὶ ὁ ἱκανὸς σφόδρα·' },
  { book_slug: 'ruth', chapter: 1, verse_num: 21, translation_code: 'grc-sblgnt', text: 'ἐγὼ πλήρης ἐπορεύθην, καὶ κενὴν ἀπέστρεψέν με ὁ Κύριος· καὶ ἱνατί καλεῖτέ με Νωεμιν, καὶ Κύριος ἐταπείνωσέν με καὶ ὁ ἱκανὸς ἐκάκωσέν με;' },
  { book_slug: 'ruth', chapter: 1, verse_num: 22, translation_code: 'grc-sblgnt', text: 'Καὶ ἐπέστρεψεν Νωεμιν καὶ Ρουθ ἡ Μωαβῖτις ἡ νύμφη αὐτῆς ἐπιστρέφουσα ἐξ ἀγροῦ Μωαβ· αὗται δὲ παρεγενήθησαν εἰς Βηθλεεμ ἐν ἀρχῇ θερισμοῦ κριθῶν.' },

  // ==========================================
  // RUTH CHAPTER 2
  // ==========================================
  { book_slug: 'ruth', chapter: 2, verse_num: 1, translation_code: 'eng-kjv', text: 'And Naomi had a kinsman of her husband\'s, a mighty man of wealth, of the family of Elimelech; and his name was Boaz.' },
  { book_slug: 'ruth', chapter: 2, verse_num: 2, translation_code: 'eng-kjv', text: 'And Ruth the Moabitess said unto Naomi, Let me now go to the field, and glean ears of corn after him in whose sight I shall find grace. And she said unto her, Go, my daughter.' },
  { book_slug: 'ruth', chapter: 2, verse_num: 3, translation_code: 'eng-kjv', text: 'And she went, and came, and gleaned in the field after the reapers: and her hap was to light on a part of the field belonging unto Boaz, who was of the kindred of Elimelech.' },
  { book_slug: 'ruth', chapter: 2, verse_num: 4, translation_code: 'eng-kjv', text: 'And, behold, Boaz came from Bethlehem, and said unto the reapers, The LORD be with you. And they answered him, The LORD bless thee.' },
  { book_slug: 'ruth', chapter: 2, verse_num: 5, translation_code: 'eng-kjv', text: 'Then said Boaz unto his servant that was set over the reapers, Whose damsel is this?' },
  { book_slug: 'ruth', chapter: 2, verse_num: 6, translation_code: 'eng-kjv', text: 'And the servant that was set over the reapers answered and said, It is the Moabitish damsel that came back with Naomi out of the country of Moab:' },
  { book_slug: 'ruth', chapter: 2, verse_num: 7, translation_code: 'eng-kjv', text: 'And she said, I pray you, let me glean and gather after the reapers among the sheaves: so she came, and hath continued even from the morning until now, that she tarried a little in the house.' },
  { book_slug: 'ruth', chapter: 2, verse_num: 8, translation_code: 'eng-kjv', text: 'Then said Boaz unto Ruth, Hearest thou not, my daughter? Go not to glean in another field, neither go from hence, but abide here fast by my maidens:' },
  { book_slug: 'ruth', chapter: 2, verse_num: 9, translation_code: 'eng-kjv', text: 'Let thine eyes be on the field that they do reap, and go thou after them: have I not charged the young men that they shall not touch thee? and when thou art athirst, go unto the vessels, and drink of that which the young men have drawn.' },
  { book_slug: 'ruth', chapter: 2, verse_num: 10, translation_code: 'eng-kjv', text: 'Then she fell on her face, and bowed herself to the ground, and said unto him, Why have I found grace in thine eyes, that thou shouldest take knowledge of me, seeing I am a stranger?' },
  { book_slug: 'ruth', chapter: 2, verse_num: 11, translation_code: 'eng-kjv', text: 'And Boaz answered and said unto her, It hath fully been shewed me, all that thou hast done unto thy mother in law since the death of thine husband: and how thou hast left thy father and thy mother, and the land of thy nativity, and art come unto a people which thou knewest not heretofore.' },
  { book_slug: 'ruth', chapter: 2, verse_num: 12, translation_code: 'eng-kjv', text: 'The LORD recompense thy work, and a full reward be given thee of the LORD God of Israel, under whose wings thou art come to trust.' },

  { book_slug: 'ruth', chapter: 2, verse_num: 1, translation_code: 'am-1875', text: 'ለኑኃሚንም ከባልዋ ወገን የሆነ ከአቤሜሌክ ቤተ ዘመድ አንድ ባለጠጋና ኃያል ሰው ነበረ፤ ስሙም ቦዔዝ ነበረ።' },
  { book_slug: 'ruth', chapter: 2, verse_num: 2, translation_code: 'am-1875', text: 'ሞዓባዊቱም ሩት ኑኃሚንን፦ በፊቱ ሞገስ ባገኘሁበት ሰው ኋላ እሸት እየለቀምሁ ወደ እርሻ ልሂድ አለቻት። እርስዋም፦ ልጄ ሆይ፥ ሂጂ አለቻት።' },
  { book_slug: 'ruth', chapter: 2, verse_num: 3, translation_code: 'am-1875', text: 'ሄደችም፥ መጥታም በአጫጆች ኋላ በእርሻ ውስጥ እሸት ለቀመች፤ ዕድልዋም ከአቤሜሌክ ወገን ለሆነው ለቦዔዝ በነበረው በእርሻው ክፍል ላይ ጣላት።' },
  { book_slug: 'ruth', chapter: 2, verse_num: 4, translation_code: 'am-1875', text: 'እነሆም፥ ቦዔዝ ከቤተ ልሔም መጣ፥ አጫጆቹንም፦ እግዚአብሔር ከእናንተ ጋር ይሁን አላቸው። እነርሱም፦ እግዚአብሔር ይባርክህ ብለው መለሱለት።' },
  { book_slug: 'ruth', chapter: 2, verse_num: 5, translation_code: 'am-1875', text: 'ቦዔዝም በአጫጆች ላይ የተሾመውን ሎሌውን፦ ይህች ቆንጆ የማን ናት? አለው።' },
  { book_slug: 'ruth', chapter: 2, verse_num: 6, translation_code: 'am-1875', text: 'በአጫጆች ላይ የተሾመውም ሎሌ መልሶ፦ ከኑኃሚን ጋር ከሞዓብ ምድር የተመለሰችው ሞዓባዊቱ ቆንጆ እርስዋ ናት፤' },
  { book_slug: 'ruth', chapter: 2, verse_num: 7, translation_code: 'am-1875', text: 'እርስዋም፦ በአጫጆች ኋላ በነዶዎች መካከል እንድለቅምና እንድሰበስብ እለምንሃለሁ አለች፤ መጥታም ከማለዳ ጀምራ እስከ አሁን ድረስ ቆየች፥ በቤትም የተቀመጠችው ጥቂት ጊዜ ብቻ ነው አለው።' },
  { book_slug: 'ruth', chapter: 2, verse_num: 8, translation_code: 'am-1875', text: 'ቦዔዝም ሩትን አላት፦ ልጄ ሆይ፥ ስሚኝ፤ በሌላ እርሻ ውስጥ እሸት ልትለቅሚ አትሂጂ፥ ከዚህም አትለፊ፥ ነገር ግን ከሴቶች ልጆቼ ጋር በዚህ ተቀመጪ።' },
  { book_slug: 'ruth', chapter: 2, verse_num: 9, translation_code: 'am-1875', text: 'ዓይኖችሽ በሚያጭዱበት እርሻ ላይ ይሁኑ፥ በኋላቸውም ሂጂ፤ እንዳይነኩሽ ጐበዞችን አላዘዝሁምን? በጠማሽም ጊዜ ወደ ዕቃዎቹ ሂጂ፥ ጐበዞቹም የቀዱትን ጠጪ።' },
  { book_slug: 'ruth', chapter: 2, verse_num: 10, translation_code: 'am-1875', text: 'በግምባርዋም ተደፍታ ወደ ምድር ሰገደችና፦ እኔ እንግዳ ስሆን እንድታውቀኝ በዐይንህ ፊት ሞገስ እንዴት አገኘሁ? አለችው።' },
  { book_slug: 'ruth', chapter: 2, verse_num: 11, translation_code: 'am-1875', text: 'ቦዔዝም መልሶ እንዲህ አላት፦ ባልሽ ከሞተ በኋላ ለአማትሽ ያደረግሽው ሁሉ፥ አባትሽንና እናትሽንም የተወለድሽበትንም ምድር ትተሽ አስቀድመሽ ወደማታውቂው ሕዝብ እንደ መጣሽ ፈጽሞ ተነግሮኛል።' },
  { book_slug: 'ruth', chapter: 2, verse_num: 12, translation_code: 'am-1875', text: 'እግዚአብሔር እንደ ሥራሽ ፍዳሽን ይክፈልሽ፤ በክንፎቹም በታች ልትጠጊ ወደ መጣሽበት ወደ እስራኤል አምላክ ወደ እግዚአብሔር ሙሉ ዋጋሽ ይሁን።' },

  { book_slug: 'ruth', chapter: 2, verse_num: 1, translation_code: 'heb-wlc', text: 'וּֽלְנָעֳמִ֞י מוֹדַ֣ע לְאִישָׁ֗הּ אִ֚ישׁ גִּבּ֣וֹר חַ֔יִל מִמִּשְׁפַּ֖חַת אֱלִימֶ֑לֶךְ וּשְׁמ֖וֹ בֹּֽעַז׃' },
  { book_slug: 'ruth', chapter: 2, verse_num: 2, translation_code: 'heb-wlc', text: 'וַתֹּאמֶר֩ ר֨וּת הַמּוֹאֲבִיָּ֜ה אֶֽל־נָעֳמִ֗י אֵֽלְכָה־נָּ֤א הַשָּׂדֶה֙ וַאֲלַקֳטָ֣ה בַשִּׁבֳּלִ֔ים אַחַ֕ר אֲשֶׁ֥ר אֶמְצָא־חֵ֖ן בְּעֵינָ֑יו וַתֹּ֥אמֶר לָ֖הּ לְכִ֥י בִתִּֽי׃' },
  { book_slug: 'ruth', chapter: 2, verse_num: 3, translation_code: 'heb-wlc', text: 'וַתֵּ֤לֶךְ וַתָּבוֹא֙ וַתְּלַקֵּ֣ט בַּשָּׂדֶ֔ה אַחֲרֵ֖י הַקֹּצְרִ֑ים וַיִּ֣קֶר מִקְרֶ֔הָ חֶלְקַ֤ת הַשָּׂדֶה֙ לְבֹ֔עַז אֲשֶׁ֖ר מִמִּשְׁפַּ֥חַת אֱלִימֶֽלֶךְ׃' },
  { book_slug: 'ruth', chapter: 2, verse_num: 4, translation_code: 'heb-wlc', text: 'וְהִנֵּה־בֹ֗עַז בָּ֚א מִבֵּ֣ית לֶ֔חֶם וַיֹּ֥אמֶר לַקּוֹצְרִ֖ים יְהוָ֣ה עִמָּכֶ֑ם וַיֹּ֥אמְרוּ ל֖וֹ יְבָרֶכְךָ֥ יְהוָֽה׃' },
  { book_slug: 'ruth', chapter: 2, verse_num: 5, translation_code: 'heb-wlc', text: 'וַיֹּ֤אמֶר בֹּ֙עַז֙ לְנַעֲר֔וֹ הַנִּצָּ֖ב עַל־הַקּוֹצְרִ֑ים לְמִ֖י הַנַּעֲרָ֥ה הַזֹּֽאת׃' },
  { book_slug: 'ruth', chapter: 2, verse_num: 6, translation_code: 'heb-wlc', text: 'וַיַּ֗עַן הַנַּ֛עַר הַנִּצָּ֥ב עַל־הַקּוֹצְרִ֖ים וַיֹּאמַ֑ר נַעֲרָ֤ה מֽוֹאֲבִיָּה֙ הִ֔יא הַשָּׁ֥בָה עִֽם־נָעֳמִ֖י מִשְּׂדֵ֥ה מוֹאָֽב׃' },
  { book_slug: 'ruth', chapter: 2, verse_num: 7, translation_code: 'heb-wlc', text: 'וַתֹּ֗אמֶר אֲלַקֳּטָה־נָּא֙ וְאָסַפְתִּ֣י בָֽעֳמָרִ֔ים אַחֲרֵ֖י הַקּוֹצְרִ֑ים וַתָּב֣וֹא וַֽתַּעֲמ֗וֹד מֵאָ֤ז הַבֹּ֙קֶר֙ וְעַד־עַ֔תָּה זֶ֛ה שִׁבְתָּ֥הּ הַבַּ֖יִת מְעָֽט׃' },
  { book_slug: 'ruth', chapter: 2, verse_num: 8, translation_code: 'heb-wlc', text: 'וַיֹּאמֶר֩ בֹּ֨עַז אֶל־ר֜וּת הֲל֧וֹא שָׁמַ֣עַתְּ בִּתִּ֗י אַל־תֵּלְכִי֙ לִלְקֹט֙ בְּשָׂדֶ֣ה אַחֵ֔ר וְגַ֛ם לֹ֥א תַעֲבוּרִ֖י מִזֶּ֑ה וְכֹ֥ה תִדְבָּקִ֖ין עִם־נַעֲרֹתָֽי׃' },
  { book_slug: 'ruth', chapter: 2, verse_num: 9, translation_code: 'heb-wlc', text: 'עֵינַ֜יִךְ בַּשָּׂדֶ֤ה אֲשֶׁר־יִקְצֹרוּן֙ וְהָלַ֣כְתְּ אַחֲרֵיהֶ֔ן הֲלוֹא֙ צִוִּ֣יתִי אֶת־הַנְּעָרִ֔ים לְבִלְתִּ֖י נָגְעֵ֑ךְ וְצָמִ֗ת וְהָלַכְתְּ֙ אֶל־הַכֵּלִ֔ים וְשָׁתִ֔ית מֵאֲשֶׁ֥ר יִשְׁאֲב֖וּן הַנְּעָרִֽים׃' },
  { book_slug: 'ruth', chapter: 2, verse_num: 10, translation_code: 'heb-wlc', text: 'וַתִּפֹּל֙ עַל־פָּנֶ֔יהָ וַתִּשְׁתַּ֖חוּ אָ֑רְצָה וַתֹּ֣אמֶר אֵלָ֗יו מַדּוּעַ֩ מָצָ֨אתִי חֵ֤ן בְּעֵינֶ֙יךָ֙ לְהַכִּירֵ֔נִי וְאָנֹכִ֖י נָכְרִיָּֽה׃' },
  { book_slug: 'ruth', chapter: 2, verse_num: 11, translation_code: 'heb-wlc', text: 'וַיַּ֤עַן בֹּ֙עַז֙ וַיֹּ֣אמֶר לָ֔הּ הֻגֵּ֨ד הֻגַּ֜ד לִ֗י כֹּ֤ל אֲשֶׁר־עָשִׂית֙ אֶת־חֲמוֹתֵ֔ךְ אַחֲרֵ֖י מ֣וֹת אִישֵׁ֑ךְ וַתַּעַזְבִ֞י אָבִ֣יךְ וְאִמֵּ֗ךְ וְאֶ֙רֶץ֙ מֽוֹלַדְתֵּ֔ךְ וַתֵּ֣לְכִ֔י אֶל־עַ֕ם אֲשֶׁ֥ר לֹא־יָדַ֖עַתְּ תְּמ֥וֹל שִׁלְשֽׁוֹם׃' },
  { book_slug: 'ruth', chapter: 2, verse_num: 12, translation_code: 'heb-wlc', text: 'יְשַׁלֵּ֥ם יְהוָ֖ה פָּעֳלֵ֑ךְ וּתְהִ֨י מַשְׂכֻּרְתֵּ֜ךְ שְׁלֵמָ֗ה מֵעִ֤ם יְהוָה֙ אֱלֹהֵ֣י יִשְׂרָאֵ֔ל אֲשֶׁר־בָּ֖את לַחֲס֥וֹת תַּֽחַת־כְּנָפָֽיו׃' },

  { book_slug: 'ruth', chapter: 2, verse_num: 1, translation_code: 'grc-sblgnt', text: 'Καὶ τῇ Νωεμιν ἦν γνωστός τῷ ἀνδρὶ αὐτῆς, ὁ δὲ ἀνὴρ δυνατὸς ἰσχύϊ ἐκ τῆς συγγενείας Ἐλιμέλεχ, καὶ ὄνομα αὐτῷ Βόος.' },
  { book_slug: 'ruth', chapter: 2, verse_num: 2, translation_code: 'grc-sblgnt', text: 'Καὶ εἶπεν Ῥοὺθ ἡ Μωαβῖτις πρὸς Νωεμιν· Πορευθῶ δὴ εἰς ἀγρὸν καὶ συνάξω ἐν τοῖς στάχυσιν κατόπισθεν οὗ ἐὰν εὕρω χάριν ἐν ὀφθαλμοῖς αὐτοῦ. εἶπεν δὲ αὐτῇ· Πορεύου, θύγατερ.' },
  { book_slug: 'ruth', chapter: 2, verse_num: 3, translation_code: 'grc-sblgnt', text: 'Καὶ ἐπορεύθη καὶ ἦλθεν καὶ συνέλεξεν ἐν τῷ ἀγρῷ κατόπισθεν τῶν θεριζόντων· καὶ περιέπεσεν περιπτώματι τῇ μερίδι τοῦ ἀγροῦ Βόος τοῦ ἐκ τῆς συγγενείας Ἐλιμέλεχ.' },
  { book_slug: 'ruth', chapter: 2, verse_num: 4, translation_code: 'grc-sblgnt', text: 'Καὶ ἰδοὺ Βόος ἦλθεν ἐκ Βηθλεεμ καὶ εἶπεν τοῖς θερίζουσιν· Κύριος μεθʼ ὑμῶν· καὶ εἶπον αὐτῷ· Εὐλογήσαι σε Κύριος.' },
  { book_slug: 'ruth', chapter: 2, verse_num: 5, translation_code: 'grc-sblgnt', text: 'Καὶ εἶπεν Βόος τῷ παιδαρίῳ αὐτοῦ τῷ ἐφεστῶτι ἐπὶ τοὺς θερίζοντας· Τίνος ἡ νεᾶνις αὕτη;' },
  { book_slug: 'ruth', chapter: 2, verse_num: 6, translation_code: 'grc-sblgnt', text: 'Καὶ ἀπεκρίθη τὸ παιδάριον τὸ ἐφεστὸς ἐπὶ τοὺς θερίζοντας καὶ εἶπεν· Ἡ παῖς ἡ Μωαβῖτίς ἐστιν ἡ ἀποστραφεῖσα μετὰ Νωεμιν ἐξ ἀγροῦ Μωαβ·' },
  { book_slug: 'ruth', chapter: 2, verse_num: 7, translation_code: 'grc-sblgnt', text: 'καὶ εἶπεν· Συλλέξω δὴ καὶ συνάξω ἐν τοῖς δράγμασιν ὀπίσω τῶν θεριζόντων· καὶ ἦλθεν καὶ ἔστη ἀπὸ πρωΐθεν καὶ ἕως ἑσπέρας, οὐ κατέπαυσεν μικρὸν ἐν τῷ ἀγρῷ.' },
  { book_slug: 'ruth', chapter: 2, verse_num: 8, translation_code: 'grc-sblgnt', text: 'Καὶ εἶπεν Βόος πρὸς Ῥούθ· Οὐκ ἤκουσας, θύγατερ; μὴ πορευθῇς συλλέξαι ἐν ἀγρῷ ἑτέρῳ, καὶ σὺ οὐ πορεύσῃ ἐντεῦθεν, ἀλλὰ ὧδε κολληθήσῃ μετὰ τῶν κορασίων μου·' },
  { book_slug: 'ruth', chapter: 2, verse_num: 9, translation_code: 'grc-sblgnt', text: 'οἱ ὀφθαλμοί σου εἰς τὸν ἀγρόν, οὗ ἐὰν θερίζωσιν, καὶ πορεύσῃ κατόπισθεν αὐτῶν· οὐχὶ ἐνετειλάμην τοῖς παιδαρίοις τοῦ μὴ ἅψασθαί σου; καὶ ὅτε διψήσεις, καὶ πορευθήσῃ εἰς τὰ σκεύη καὶ πίεσαι ὅθεν ἂν ὑδρεύωνται τὰ παιδάρια.' },
  { book_slug: 'ruth', chapter: 2, verse_num: 10, translation_code: 'grc-sblgnt', text: 'Καὶ ἔπεσεν ἐπὶ πρόσωπον αὐτῆς καὶ προσεκύνησεν ἐπὶ τὴν γῆν καὶ εἶπεν πρὸς αὐτόν· Τί ὅτι εὗρον χάριν ἐν ὀφθαλμοῖς σου τοῦ ἐπιγνῶναί με, καὶ ἐγώ εἰμι ξένη;' },
  { book_slug: 'ruth', chapter: 2, verse_num: 11, translation_code: 'grc-sblgnt', text: 'Καὶ ἀπεκρίθη Βόος καὶ εἶπεν αὐτῇ· Ἀπαγγελίᾳ ἀπηγγέλη μοι πάντα ὅσα ἐποίησας μετὰ τῆς πενθερᾶς σου μετὰ τὸ ἀποθανεῖν τὸν ἄνδρα σου, καὶ πῶς κατέλιπες τὸν πατέρα σου καὶ τὴν μητέρα σου καὶ τὴν γῆν τῆς γενέσεώς σου καὶ ἐπορεύθης πρὸς λαὸν ὃν οὐκ ᾔδεις ἐχθὲς καὶ τρίτην·' },
  { book_slug: 'ruth', chapter: 2, verse_num: 12, translation_code: 'grc-sblgnt', text: 'ἀποτίσαι Κύριος τὸ ἔργον σου, καὶ γένοιτο ὁ μισθός σου πλήρης παρὰ Κυρίου θεοῦ Ἰσραήλ, πρὸς ὃν ἦλθες πεποιθέναι ὑπὸ τὰς πτέρυγας αὐτοῦ.' },

  // ==========================================
  // RUTH CHAPTER 3
  // ==========================================
  { book_slug: 'ruth', chapter: 3, verse_num: 1, translation_code: 'eng-kjv', text: 'Then Naomi her mother in law said unto her, My daughter, shall I not seek rest for thee, that it may be well with thee?' },
  { book_slug: 'ruth', chapter: 3, verse_num: 2, translation_code: 'eng-kjv', text: 'And now is not Boaz of our kindred, with whose maidens thou wast? Behold, he winnoweth barley to night in the threshingfloor.' },
  { book_slug: 'ruth', chapter: 3, verse_num: 3, translation_code: 'eng-kjv', text: 'Wash thyself therefore, and anoint thee, and put thy raiment upon thee, and get thee down to the floor: but make not thyself known unto the man, until he shall have done eating and drinking.' },
  { book_slug: 'ruth', chapter: 3, verse_num: 4, translation_code: 'eng-kjv', text: 'And it shall be, when he lieth down, that thou shalt mark the place where he shall lie, and thou shalt go in, and uncover his feet, and lay thee down; and he will tell thee what thou shalt do.' },
  { book_slug: 'ruth', chapter: 3, verse_num: 5, translation_code: 'eng-kjv', text: 'And she said unto her, All that thou sayest unto me I will do.' },

  { book_slug: 'ruth', chapter: 3, verse_num: 1, translation_code: 'am-1875', text: 'አማትዋም ኑኃሚን እንዲህ አለቻት፦ ልጄ ሆይ፥ መልካም እንዲሆንልሽ ዕረፍት ልፈልግልሽ አይገባኝምን?' },
  { book_slug: 'ruth', chapter: 3, verse_num: 2, translation_code: 'am-1875', text: 'አሁንም ከሴቶች ልጆቹ ጋር የነበርሽው ቦዔዝ ዘመዳችን አይደለምን? እነሆ፥ እርሱ ዛሬ በሌሊት በአውድማ ላይ ገብስ ያበጥራል።' },
  { book_slug: 'ruth', chapter: 3, verse_num: 3, translation_code: 'am-1875', text: 'እንግዲህ ታጠቢ፥ ቅባትም ተቀቢ፥ ልብስሽንም ልበሺ፥ ወደ አውድማውም ውረጂ፤ ነገር ግን እስኪበላና እስኪጠጣ ድረስ ሰውየው አይወቅሽ።' },
  { book_slug: 'ruth', chapter: 3, verse_num: 4, translation_code: 'am-1875', text: 'በተኛም ጊዜ የሚተኛበትን ስፍራ ተመልከቺ፥ ገብተሽም የእግሩን ልብስ ግለጪና ተኚ፤ የምታደርጊውንም እርሱ ይነግርሻል።' },
  { book_slug: 'ruth', chapter: 3, verse_num: 5, translation_code: 'am-1875', text: 'እርስዋም፦ ያልሽኝን ሁሉ አደርጋለሁ አለቻት።' },

  { book_slug: 'ruth', chapter: 3, verse_num: 1, translation_code: 'heb-wlc', text: 'וַתֹּ֥אמֶר לָ֖הּ נָעֳמִ֣י חֲמוֹתָ֑הּ בִּתִּ֕י הֲלֹ֧א אֲבַקֶּשׁ־לָ֛ךְ מָנ֖וֹחַ אֲשֶׁ֥ר יִֽיטַב־לָֽךְ׃' },
  { book_slug: 'ruth', chapter: 3, verse_num: 2, translation_code: 'heb-wlc', text: 'וְעַתָּ֗ה הֲלֹ֥א בֹ֙עַז֙ מֹֽדַעְתָּ֔נוּ אֲשֶׁ֥ר הָיִ֖ית אֶת־נַעֲרוֹתָ֑יו הִנֵּה־ה֗וּא זֹרֶ֛ה אֶת־גֹּ֥רֶן הַשְּׂעֹרִ֖ים הַלָּֽיְלָה׃' },
  { book_slug: 'ruth', chapter: 3, verse_num: 3, translation_code: 'heb-wlc', text: 'וְרָחַ֣צְתְּ ׀ וָסַ֗כְתְּ וְשַׂ֧מְתְּ שִׂמְלֹתַ֛יִךְ עָלַ֖יִךְ וְיָרַ֣דְתְּ הַגֹּ֑רֶן אַל־תִּוָּדְעִ֣י לָאִ֔ישׁ עַ֥ד כַּלֹּת֖וֹ לֶאֱכֹ֥ל וְלִשְׁתּֽוֹת׃' },
  { book_slug: 'ruth', chapter: 3, verse_num: 4, translation_code: 'heb-wlc', text: 'וִיהִ֣י בְשָׁכְב֗וֹ וְיָדַ֙עַתְּ֙ אֶת־הַמָּקוֹם֙ אֲשֶׁ֣ר יִשְׁכַּב־שָׁ֔ם וּבָ֛את וְגִלִּ֥ית מַרְגְּלֹתָ֖יו וְשָׁכָ֑בְתְּ וְהוּא֙ יַגִּ֣יד לָ֔ךְ אֵ֖ת אֲשֶׁ֥ר תַּעֲשִֽׂין׃' },
  { book_slug: 'ruth', chapter: 3, verse_num: 5, translation_code: 'heb-wlc', text: 'וַתֹּ֖אמֶר אֵלֶ֑יהָ כֹּ֛ל אֲשֶׁר־תֹּאמְרִ֥י אֵלַ֖י אֶֽעֱשֶֽׂה׃' },

  { book_slug: 'ruth', chapter: 3, verse_num: 1, translation_code: 'grc-sblgnt', text: 'Καὶ εἶπεν αὐτῇ Νωεμιν ἡ πενθερὰ αὐτῆς· Θύγατερ, οὐ μὴ ζητήσω σοι ἀνάπαυσιν, ἵνα εὖ γένηταί σοι;' },
  { book_slug: 'ruth', chapter: 3, verse_num: 2, translation_code: 'grc-sblgnt', text: 'Καὶ νῦν οὐχὶ Βόος γνωστός ἡμῶν, οὗ ἦς μετὰ τῶν κορασίων αὐτοῦ; ἰδοὺ αὐτὸς λικμᾷ τὸν ἅλωνα τῶν κριθῶν ταύτῃ τῇ νυκτί.' },
  { book_slug: 'ruth', chapter: 3, verse_num: 3, translation_code: 'grc-sblgnt', text: 'Σὺ δὲ λούσῃ καὶ ἀλείψῃ καὶ περιθήσεις τὸν ἱματισμόν σου ἐπὶ σὲ καὶ ἀναβήσῃ εἰς τὸν ἅλωνα· μὴ γνωρισθῇς τῷ ἀνδρὶ ἕως οὗ συντελέσῃ πιεῖν καὶ φαγεῖν.' },
  { book_slug: 'ruth', chapter: 3, verse_num: 4, translation_code: 'grc-sblgnt', text: 'Καὶ ἔσται ἐν τῷ κοιμηθῆναι αὐτὸν καὶ γνώσῃ τὸν τόπον, ὅπου κοιμᾶται ἐκεῖ, καὶ ἐλεύσῃ καὶ ἀποκαλύψεις τὰ πρὸς ποδῶν αὐτοῦ καὶ κοιμηθήσῃ· καὶ αὐτὸς ἀπαγγελεῖ σοι ἃ ποιήσεις.' },
  { book_slug: 'ruth', chapter: 3, verse_num: 5, translation_code: 'grc-sblgnt', text: 'Καὶ εἶπεν Ῥοὺθ πρὸς αὐτήν· Πάντα, ὅσα ἐὰν εἴπῃς, ποιήσω.' },

  // ==========================================
  // RUTH CHAPTER 4
  // ==========================================
  { book_slug: 'ruth', chapter: 4, verse_num: 1, translation_code: 'eng-kjv', text: 'Then went Boaz up to the gate, and sat him down there: and, behold, the kinsman of whom Boaz spake came by; unto whom he said, Ho, such a one! turn aside, sit down here. And he turned aside, and sat down.' },
  { book_slug: 'ruth', chapter: 4, verse_num: 2, translation_code: 'eng-kjv', text: 'And he took ten men of the elders of the city, and said, Sit ye down here. And they sat down.' },
  { book_slug: 'ruth', chapter: 4, verse_num: 3, translation_code: 'eng-kjv', text: 'And he said unto the kinsman, Naomi, that is come again out of the country of Moab, selleth a parcel of land, which was our brother Elimelech\'s:' },
  { book_slug: 'ruth', chapter: 4, verse_num: 4, translation_code: 'eng-kjv', text: 'And I thought to advertise thee, saying, Buy it before the inhabitants, and before the elders of my people. If thou wilt redeem it, redeem it: but if thou wilt not redeem it, then tell me, that I may know: for there is none to redeem it beside thee; and I am after thee. And he said, I will redeem it.' },
  { book_slug: 'ruth', chapter: 4, verse_num: 14, translation_code: 'eng-kjv', text: 'And the women said unto Naomi, Blessed be the LORD, which hath not left thee this day without a kinsman, that his name may be famous in Israel.' },
  { book_slug: 'ruth', chapter: 4, verse_num: 17, translation_code: 'eng-kjv', text: 'And the women her neighbours gave it a name, saying, There is a son born to Naomi; and they called his name Obed: he is the father of Jesse, the father of David.' },

  { book_slug: 'ruth', chapter: 4, verse_num: 1, translation_code: 'am-1875', text: 'ቦዔዝም ወደ አደባባይ ወጥቶ በዚያ ተቀመጠ፤ እነሆም፥ ቦዔዝ የተናገረለት ዘመድ አለፈ፤ እርሱም፦ ወዳጄ ሆይ፥ ፈቀቅ በልና በዚህ ተቀመጥ አለው። እርሱም ፈቀቅ ብሎ ተቀመጠ።' },
  { book_slug: 'ruth', chapter: 4, verse_num: 2, translation_code: 'am-1875', text: 'ከከተማይቱም ሽማግሌዎች ዐሥር ሰዎች ወስዶ፦ በዚህ ተቀመጡ አላቸው። እነርሱም ተቀመጡ።' },
  { book_slug: 'ruth', chapter: 4, verse_num: 3, translation_code: 'am-1875', text: 'ለዘመዱም እንዲህ አለው፦ ከሞዓብ ምድር የተመለሰችው ኑኃሚን የወንድማችን የአቤሜሌክ የነበረውን የእርሻውን ክፍል ልትሸጥ ነው።' },
  { book_slug: 'ruth', chapter: 4, verse_num: 4, translation_code: 'am-1875', text: 'እኔም፦ በአደባባይ በተቀመጡትና በሕዝቤ ሽማግሌዎች ፊት ግዛው ብዬ ልነግርህ አሰብሁ፤ ብትቤዠው፥ ዋጀው፤ ባትቤዠው ግን ከአንተ በቀር የሚቤዥ የለምና፥ እኔም ከአንተ በኋላ ነኝና እንድያውቅ ንገረኝ አለው። እርሱም፦ እኔ እቤዠዋለሁ አለ።' },
  { book_slug: 'ruth', chapter: 4, verse_num: 14, translation_code: 'am-1875', text: 'ሴቶቹም ኑኃሚንን አሏት፦ ዛሬ የሚቤዥህን ያላሳጣሽ እግዚአብሔር ይመስገን፥ ስሙም በእስራኤል ዘንድ የታወቀ ይሁን።' },
  { book_slug: 'ruth', chapter: 4, verse_num: 17, translation_code: 'am-1875', text: 'የጐረቤት ሴቶችም፦ ለኑኃሚን ወንድ ልጅ ተወለደላት እያሉ ስም አወጡለት፤ ስሙንም ኢዮቤድ ብለው ጠሩት፤ እርሱም የዳዊት አባት የእሴይ አባት ነው።' },

  { book_slug: 'ruth', chapter: 4, verse_num: 1, translation_code: 'heb-wlc', text: 'וּבֹ֨עַז עָלָ֣ה הַשַּׁעַר֮ וַיֵּ֣שֶׁב שָׁם֒ וְהִנֵּ֨ה הַגֹּאֵ֤ל עֹבֵר֙ אֲשֶׁ֣ר דִּבֶּר־בֹּ֔עַז וַיֹּ֛אמֶר ס֥וּרָה שְׁבָה־פֹּ֖ה פְּלֹנִ֣י אַלְמֹנִ֑י וַיָּ֖סַר וַיֵּשֵֽׁב׃' },
  { book_slug: 'ruth', chapter: 4, verse_num: 2, translation_code: 'heb-wlc', text: 'וַיִּקַּ֞ח עֲשָׂרָ֧ה אֲנָשִׁ֛ים מִזִּקְנֵ֥י הָעִ֖יר וַיֹּ֣אמֶר שְׁבוּ־פֹ֑ה וַיֵּשֵֽׁבוּ׃' },
  { book_slug: 'ruth', chapter: 4, verse_num: 3, translation_code: 'heb-wlc', text: 'וַיֹּ֙אמֶר֙ לַגֹּאֵ֔ל חֶלְקַת֙ הַשָּׂדֶ֔ה אֲשֶׁ֥ר לְאָחִ֖ינוּ לֶאֱלִימֶ֑לֶךְ מָכְרָ֣ה נָעֳמִ֔י הַשָּׁ֖בָה מִשְּׂדֵ֥ה מוֹאָֽב׃' },
  { book_slug: 'ruth', chapter: 4, verse_num: 4, translation_code: 'heb-wlc', text: 'וַאֲנִ֨י אָמַ֜רְתִּי אֶגְלֶ֧ה אָזְנְךָ֣ לֵאמֹ֗ר קְ֠נֵה נֶ֥גֶד הַיֹּשְׁבִים֮ וְנֶ֣גֶד זִקְנֵ֣י עַמִּי֒ אִם־תִּגְאַל֙ גְּאָ֔ל וְאִם־לֹ֨א יִגְאַ֜ל הַגִּ֣ידָה לִּ֗י וְאֵדַע֙ כִּ֣י אֵ֤ין זוּלָֽתְךָ֙ לִגְא֔וֹל וְאָנֹכִ֖י אַחֲרֶ֑יךָ וַיֹּ֖אמֶר אָנֹכִ֥י אֶגְאָֽל׃' },
  { book_slug: 'ruth', chapter: 4, verse_num: 14, translation_code: 'heb-wlc', text: 'וַתֹּאמַ֤רְנָה הַנָּשִׁים֙ אֶֽל־נָעֳמִ֔י בָּר֣וּךְ יְהוָ֔ה אֲ֠שֶׁר לֹ֣א הִשְׁבִּ֥ית לָ֛ךְ גֹּאֵ֖ל הַיּ֑וֹם וְיִקָּרֵ֥א שְׁמ֖וֹ בְּיִשְׂרָאֵֽל׃' },
  { book_slug: 'ruth', chapter: 4, verse_num: 17, translation_code: 'heb-wlc', text: 'וַתִּקְרֶאנָה֩ ל֨וֹ הַשְּׁכֵנ֥וֹת שֵׁם֙ לֵאמֹ֔ר יֻלַּד־בֵּ֖ן לְנָעֳמִ֑י וַתִּקְרֶ֤אנָה שְׁמוֹ֙ עוֹבֵ֔ד ה֥וּא אֲבִי־יִשַׁ֖י אֲבִ֥י דָוִֽד׃' },

  { book_slug: 'ruth', chapter: 4, verse_num: 1, translation_code: 'grc-sblgnt', text: 'Καὶ Βόος ἀνέβη ἐπὶ τὴν πύλην καὶ ἐκάθισεν ἐκεῖ. καὶ ἰδοὺ ὁ ἀγχιστεὺς παρεπορεύετο ὃν εἶπεν Βόος, καὶ εἶπεν πρὸς αὐτὸν Βόος· Ἔκκλινον, κάθισον ὧδε, κρύφιε. καὶ ἐξέκλινεν καὶ ἐκάθισεν.' },
  { book_slug: 'ruth', chapter: 4, verse_num: 2, translation_code: 'grc-sblgnt', text: 'Καὶ ἔλαβεν Βόος δέκα ἄνδρας ἀπὸ τῶν πρεσβυτέρων τῆς πόλεως καὶ εἶπεν· Καθίσατε ὧδε. καὶ ἐκάθισαν.' },
  { book_slug: 'ruth', chapter: 4, verse_num: 3, translation_code: 'grc-sblgnt', text: 'Καὶ εἶπεν Βόος τῷ ἀγχιστεῖ· Τὴν μερίδα τοῦ ἀγροῦ, ἥ ἐστιν τοῦ ἀδελφοῦ ἡμῶν τοῦ Ἐλιμέλεχ, ἀποδέδοται Νωεμιν ἡ ἐπιστρέφουσα ἐξ ἀγροῦ Μωαβ·' },
  { book_slug: 'ruth', chapter: 4, verse_num: 4, translation_code: 'grc-sblgnt', text: 'κἀγὼ εἶπα· Ἀποκαλύψω τὸ οὖς σου λέγων· Κτῆσαι ἐναντίον τῶν καθημένων καὶ ἐναντίον τῶν πρεσβυτέρων τοῦ λαοῦ μου· εἰ ἀγχιστεύεις, ἀγχίστευε· εἰ δὲ μὴ ἀγχιστεύεις, ἀνάγγειλόν μοι καὶ γνώσομαι, ὅτι οὐκ ἔστιν πάρεξ σοῦ τοῦ ἀγχιστεῦσαι, κἀγώ εἰμι μετὰ σέ. ὁ δὲ εἶπεν· Ἐγώ εἰμι ἀγχιστεύσω.' },
  { book_slug: 'ruth', chapter: 4, verse_num: 14, translation_code: 'grc-sblgnt', text: 'Καὶ εἶπαν αἱ γυναῖκες πρὸς Νωεμιν· Εὐλογητὸς Κύριος, ὃς οὐ κατέλυσέν σοι σήμερον τὸν ἀγχιστέα, καὶ καλέσαι τὸ ὄνομά σου ἐν Ἰσραήλ·' },
  { book_slug: 'ruth', chapter: 4, verse_num: 17, translation_code: 'grc-sblgnt', text: 'καὶ ἐκάλεσαν αὐτοῦ αἱ γείτονες ὄνομα λέγουσαι· Ἐτέχθη υἱὸς τῇ Νωεμιν· καὶ ἐκάλεσαν τὸ ὄνομα αὐτοῦ Ὠβήδ· οὗτος πατὴρ Ἰεσσαὶ πατρὸς Δαυίδ.' },
];
